CREATE DATABASE IF NOT EXISTS speedZone;
USE speedZone;

CREATE TABLE IF NOT EXISTS usuario(
id_usuario INT PRIMARY KEY AUTO_INCREMENT,
primeiro_nome VARCHAR(50),
ultimo_nome VARCHAR(50),
email VARCHAR(150) UNIQUE,
cpf VARCHAR(14) UNIQUE,
cargo ENUM('Funcionario', 'Administrador', 'Cliente'),
status_conta ENUM('Ativo','Bloqueado','Desativado'),
cep VARCHAR(9),
rua VARCHAR(150),
numero INT,
complemento VARCHAR(100),
bairro VARCHAR(100),
cidade VARCHAR(150),
estado VARCHAR(3),
senha VARCHAR(255),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS suporte(
id_chamado INT PRIMARY KEY AUTO_INCREMENT,
id_cliente INT,
nome_cliente VARCHAR(150),
email VARCHAR(150),
tipo ENUM('Duvida sobre um pedido','Informações sobre produto','Problema com Pagamento','Problemas Tecnicos/Erros no site', 'Outros Assuntos'),
status_pedido ENUM('Ativo','Resolvido'),
descricao VARCHAR(255),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM suporte;

CREATE TABLE IF NOT EXISTS pedidos(
id_pedido INT PRIMARY KEY AUTO_INCREMENT,
cod_pedido VARCHAR(20) UNIQUE,
id_cliente INT,
id_produto INT,
valor_total DECIMAL(10,2), 
status_pedido ENUM('Entregue','Em Processo de entrega','Cancelado')	,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS produtos(
id_produto INT PRIMARY KEY AUTO_INCREMENT,
cod_produto VARCHAR(10),
nome_produto VARCHAR(150),
descricao_produto VARCHAR(255),
preco DECIMAL(10,2),
qtd_estoque INT,
categoria ENUM(
    'pistoes',
    'bielas',
    'virabrequins',
    'comando_valvulas',
    'tuchos_balancins',
    'juntas_motor',
    'kit_stroker',
    'kit_turbo',
    'turbina',
    'supercharger',
    'intercooler',
    'wastegate',
    'blowoff_valve',
    'tubulacoes_turbo',
    'filtro_ar_esportivo',
    'kit_admissao_direta',
    'corpo_borboleta',
    'coletor_admissao',
    'bomba_combustivel',
    'bico_injetor',
    'regulador_pressao_combustivel',
    'fuel_rail',
    'coletor_escape',
    'downpipe',
    'midpipe',
    'catback',
    'valvula_escapamento',
    'silencioso_esportivo',
    'ecu_programavel',
    'reprogramacao_ecu',
    'piggyback',
    'boost_controller',
    'sensores',
    'wideband',
    'data_logger',
    'embreagem_esportiva',
    'volante_motor_aliviado',
    'short_shifter',
    'diferencial_lsd',
    'kit_cambio',
    'coilover',
    'kit_suspensao_ar',
    'molas_esportivas',
    'barra_estabilizadora',
    'camber_kit',
    'bracos_regulaveis',
    'buchas_poliuretano',
    'kit_big_brake',
    'disco_freio',
    'pastilha_esportiva',
    'mangueira_malha_aco',
    'fluido_freio',
    'radiador',
    'ventoinha',
    'mangueira_silicone',
    'termostato_esportivo',
    'radiador_oleo',
    'reservatorio_expansao',
    'aerofolio',
    'splitter_dianteiro',
    'difusor_traseiro',
    'saias_laterais',
    'capo_fibra',
    'grade_frontal',
    'scoop_capo',
    'roda_esportiva',
    'roda_beadlock',
    'pneu_semi_slick',
    'pneu_slick',
    'espacador_roda',
    'porca_esportiva',
    'farol_led',
    'lanterna_traseira',
    'drl',
    'barra_led',
    'kit_xenon',
    'banco_concha',
    'volante_esportivo',
    'pedaleira',
    'tapete_personalizado',
    'manopla_cambio',
    'painel_digital',
    'manometro',
    'santo_antonio',
    'cinto_4pontos',
    'extintor_incendio',
    'chave_geral',
    'torquimetro',
    'scanner_obd2',
    'ferramenta_montagem',
    'medidor_compressao',
    'kit_stage1',
    'kit_stage2',
    'kit_stage3',
    'kit_swap_motor',
    'kit_track_day',
    'kit_drift',
    'wrap_automotivo',
    'pelicula',
    'adesivos',
    'placa_expositora',
    'capa_automotiva'
  ) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM pedidos;
SELECT * FROM usuario;

CREATE TABLE IF NOT EXISTS cupons (
    id_cupom INT PRIMARY KEY AUTO_INCREMENT,
    codigo VARCHAR(20) UNIQUE NOT NULL,
    tipo ENUM('percentual', 'fixo') NOT NULL,
    valor DECIMAL(10, 2) NOT NULL,
    data_expiracao DATE,
    uso_maximo INT DEFAULT NULL,
    usos_atuais INT DEFAULT 0,
    status ENUM('Ativo', 'Inativo') DEFAULT 'Ativo',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
